---
title: "Create Graphs"
author: "Julie Le Borgne"
date: "25/05/2020"
output: html_document
---



```{r}
library(SMCA)
library(ggpubr)
library(ggplot2)
```

```{r}
data(cheese)

```

On crée une partition des individus sur les villes et des modalités sur les variables. 

```{r}
c1 <- 1
c2 <- 1.8
Gvar <- partition_variables(cheese)
# vect <- sample(c("a", "b"), size = ncol(cheese), replace = T)
# Gvar <- partition_select(vect, cheese, choice = "var")
Gobs <- partition_select (cheese [,3])

```

```{r}
res.smca1 <- SMCA(cheese, c1 = c1, c2 = c1, Gcol = Gvar, Grow = Gobs, n = 10, init="svd")
# res.smca2 <- SMCA(cheese, c1 = c1, c2 = c2, n = 10, Grow = Gobs)
res.smca2 <- SMCA(cheese, c1 = c1, c2 = c2, Gcol = Gvar, Grow = Gobs, n = 10, init="svd")

```

```{r}
screeplot_new(res.smca1, sort.comp = F)
screeplot_new(res.smca2, sort.comp = F)

```


```{r}
plot_SMCA(res.smca1, habillage = 3)
plot_SMCA(res.smca1, habillage = 3, axes = c(3,4))

plot_SMCA(res.smca2, habillage = 3)
plot_SMCA(res.smca2, habillage = 3, axes = c(3,4))
```


```{r}
plot_SMCA(res.smca1, choix = "var", aff.noms = T) + theme(legend.position = "none")
plot_SMCA(res.smca1, choix = "var", aff.noms = T,  axes = c(3,4)) + theme(legend.position = "none")

plot_SMCA(res.smca2, choix = "var", aff.noms = T) + theme(legend.position = "none")
plot_SMCA(res.smca2, choix = "var", aff.noms = T,  axes = c(3,4)) + theme(legend.position = "none")
```
```{r}

plot_SMCA(res.smca1, choix = "mod", aff.noms = T) + theme(legend.position = "none")
plot_SMCA(res.smca1, choix = "mod", aff.noms = T,  axes = c(3,4)) + theme(legend.position = "none")

plot_SMCA(res.smca2, choix = "mod", aff.noms = T) + theme(legend.position = "none")
plot_SMCA(res.smca2, choix = "mod", aff.noms = T,  axes = c(3,4)) + theme(legend.position = "none")
```
